### ISSUE TITLE
arrays of 8byte dtypes?

### ISSUE THREAD

**Issue by padraic-mcatee** [hughhyndman/pgtokdb#4]
Using Postgres 10. `INT8ARRAYOID` and `FLOAT8ARRAYOID` are no longer defined in `src/include/catalog/pg_type.h`, but I see where their oid's are defined (#'s 1016 and 1022, respectively). Is anyone familiar with this issue?

**Comment by hughhyndman** [comment]
I struggled with this when I wrote the extension. I used: catalog/pg_type_d.h to get those types. Let me know if that works in PG 10.
